<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonKoupitPrvniDostupny</name>
   <tag></tag>
   <elementGuidId>6ba2b3d5-55b8-4080-8caa-f11a91e91ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = concat(&quot;javascript:boxOrder(7484048, null, quantity, &quot; , &quot;'&quot; , &quot;SPO&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;AlzaOnly&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Koupit' or . = 'Koupit')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class,&quot;inStockAvailability&quot;)])[1]//a[@class=&quot;btnk1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d257f3f-791c-459c-8839-13d8b9e4bc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnk1</value>
      <webElementGuid>4fb4c24e-6af5-4db1-ab64-aacf0fce3cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:boxOrder(7484048, null, quantity, 'SPO', 'AlzaOnly')</value>
      <webElementGuid>97c5a323-ee4b-4eca-aee5-f3d6f8460e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lb-action</name>
      <type>Main</type>
      <value>buy</value>
      <webElementGuid>d18f014d-b104-421b-a1b4-528efeb9a73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Koupit</value>
      <webElementGuid>88cbac32-6346-4d40-a3c5-9437f0aced09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boxes&quot;)/div[@class=&quot;box browsingitem js-box canBuy inStockAvailability last firstRow&quot;]/div[@class=&quot;bottom&quot;]/div[@class=&quot;price&quot;]/span[@class=&quot;btnkx canc canwatchdog cannotChangeQuantity&quot;]/div[1]/div[@class=&quot;btnkx-inner&quot;]/a[@class=&quot;btnk1&quot;]</value>
      <webElementGuid>f8bfd51a-cf84-4c84-8add-cf3f603bf0a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='boxes']/div[3]/div[2]/div/span/div/div/a</value>
      <webElementGuid>dc875cfb-e1db-420d-8e1a-d04cb7387c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Koupit')]</value>
      <webElementGuid>97bb15a8-88b9-4d5e-9a6e-aea30699cef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backbone One PS5 Edition pro iPhone - Mobile Gaming Controller'])[1]/following::a[1]</value>
      <webElementGuid>bc30a1ba-6b0b-4a78-8afd-d96560785883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MSX005DS7'])[1]/following::a[3]</value>
      <webElementGuid>58b3e7fe-0ee9-4129-ad61-4fab1f6ed399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skladem > 5 ks'])[3]/preceding::a[1]</value>
      <webElementGuid>b9351475-bb97-4a8f-a716-808356bf70b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objednací kód:'])[3]/preceding::a[1]</value>
      <webElementGuid>95fff1f7-0005-4639-8b9f-d9111b4f2504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Koupit']/parent::*</value>
      <webElementGuid>032ffe7a-0d30-48d1-adb6-79accae4719f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:boxOrder(7484048, null, quantity, 'SPO', 'AlzaOnly')&quot;)]</value>
      <webElementGuid>a3eb9ef5-1315-4e58-98c0-886dafd2cf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/span/div/div/a</value>
      <webElementGuid>ddc3a213-ec07-4d6c-bd7e-3d947a01601c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:boxOrder(7484048, null, quantity, &quot; , &quot;'&quot; , &quot;SPO&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;AlzaOnly&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Koupit' or . = 'Koupit')]</value>
      <webElementGuid>2fc771db-b13a-4889-8a6d-c22cc8f5eebf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
