<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonSnezSusenky</name>
   <tag></tag>
   <elementGuidId>8186432d-cd75-4442-aea9-545bff3378ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:Alza.Web.Cookies.acceptAllCookies();' and (text() = 'Rozumím' or . = 'Rozumím')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btnx.cookies-info__button.js-cookies-info-accept
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='rootHtml']/body/div[7]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1471a96e-ad9e-482c-b573-72844c93264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnx cookies-info__button js-cookies-info-accept</value>
      <webElementGuid>c0254760-7c54-4590-ba61-d3094599ffe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-api-url</name>
      <type>Main</type>
      <value>https://webapi.alza.cz/api/visitors/6719750153/v1/activities</value>
      <webElementGuid>c7a93c5c-0976-48d7-ad0e-01b2896f0cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-type-value</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>429bb72e-42ba-4b85-8eb2-37c9d1646632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-id-value</name>
      <type>Main</type>
      <value>1023</value>
      <webElementGuid>3f865f30-d3c4-4c34-9ae0-2baff090e488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:Alza.Web.Cookies.acceptAllCookies();</value>
      <webElementGuid>e0f73274-9f0d-4a82-a63f-417f5b30b78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rozumím</value>
      <webElementGuid>be0139df-7cfb-4a73-aaf7-82d1949b0845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootHtml&quot;)/body[@class=&quot;default alza-cz alza scrollbarhidden&quot;]/div[@class=&quot;js-cookies-info cookies-info cols-3&quot;]/div[@class=&quot;cookies-info__container&quot;]/div[@class=&quot;cookies-info__inner&quot;]/div[@class=&quot;cookies-info__buttons&quot;]/a[@class=&quot;btnx cookies-info__button js-cookies-info-accept&quot;]</value>
      <webElementGuid>19117d5e-4b31-40ac-99d4-4b0f91639c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='rootHtml']/body/div[7]/div/div/div[2]/a</value>
      <webElementGuid>962e7004-1f5e-4e0c-9d5f-91eb55cd27c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rozumím')]</value>
      <webElementGuid>1e820f78-42d2-4989-bb1e-85417dbd3194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podmínkách ochrany os. údajů'])[1]/following::a[1]</value>
      <webElementGuid>ccb9951e-4f00-4111-8c3e-c54dcbc837bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Více o Vašich právech'])[1]/following::a[2]</value>
      <webElementGuid>eb212e98-e7d6-41b8-9848-814925091813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podrobné nastavení'])[1]/preceding::a[1]</value>
      <webElementGuid>830d7d9a-c3c6-4877-a573-261c3724cdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odmítnout vše'])[1]/preceding::a[2]</value>
      <webElementGuid>e062b209-3af7-466e-b5cd-538bc5777c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rozumím']/parent::*</value>
      <webElementGuid>3a728646-0d56-4a78-ae30-f1f3023995f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:Alza.Web.Cookies.acceptAllCookies();')]</value>
      <webElementGuid>53870197-cb06-405a-8298-2c5f8b2affe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/a</value>
      <webElementGuid>8354dd4c-4c85-4735-9088-979f069bf0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:Alza.Web.Cookies.acceptAllCookies();' and (text() = 'Rozumím' or . = 'Rozumím')]</value>
      <webElementGuid>413c256b-3811-4cc1-bb62-f0f436776a2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
