<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonAkceZavrit</name>
   <tag></tag>
   <elementGuidId>22471bf2-a062-4c46-bad0-eb75c57bf3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;alzaDialog&quot;)/div[@class=&quot;close&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alzaDialog > div.close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alzaDialog']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44eec1d7-59f5-4be9-ba44-741b94c2c5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>4129ed91-69f8-4f44-bce6-4499a07773b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alzaDialog&quot;)/div[@class=&quot;close&quot;]</value>
      <webElementGuid>032168ca-13bd-48a1-89a1-f3519be37be6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alzaDialog']/div[2]</value>
      <webElementGuid>6e70144d-2a90-4abb-afc8-7dd2cb18105b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[2]</value>
      <webElementGuid>2c21f335-6f48-430b-8345-1607b8ba59ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
