<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanCenaProduktu</name>
   <tag></tag>
   <elementGuidId>ea6b39a7-18a4-4dff-9fcc-d25b65d83af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.price-box.js-price-box.price-box--Normal.price-box--location-box > div.price-box__prices > span.price-box__price-text > span.price-box__price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class,&quot;inStockAvailability&quot;)])[1]//span[@class=&quot;price-box__price&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c70d3cba-ec80-4f1c-8eaa-e60347ed61d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price-box__price</value>
      <webElementGuid>f6cdc286-4b47-4da9-b922-6fb452dc762e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16 989,-</value>
      <webElementGuid>c9afc294-0fc4-4d69-9e81-70025545380c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boxes&quot;)/div[@class=&quot;box browsingitem js-box canBuy inStockAvailability last&quot;]/div[@class=&quot;bottom&quot;]/div[@class=&quot;price&quot;]/div[@class=&quot;price__price-box-wrapper&quot;]/div[@class=&quot;price-box js-price-box price-box--Normal price-box--location-box&quot;]/div[@class=&quot;price-box__prices&quot;]/span[@class=&quot;price-box__price-text&quot;]/span[@class=&quot;price-box__price&quot;]</value>
      <webElementGuid>98f4b6f8-6893-4408-a07e-7282adc10b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='boxes']/div[6]/div[2]/div/div/div/div/span/span</value>
      <webElementGuid>84d5a810-163f-404b-8f69-5a360f50b444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thrustmaster T-GT II'])[1]/following::span[3]</value>
      <webElementGuid>63491bd0-acae-4a14-ba23-66728060d757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FNT008a'])[1]/following::span[7]</value>
      <webElementGuid>895e2678-9253-4bf8-9e35-26467748cb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koupit'])[1]/preceding::span[1]</value>
      <webElementGuid>dfae2095-d5bb-4407-bfa2-65423a4a1683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skladem 2 ks'])[1]/preceding::span[2]</value>
      <webElementGuid>5b8ef59b-35c4-48ae-b2e1-9f4d0f6d7225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16 989,-']/parent::*</value>
      <webElementGuid>bdaf1b55-58d3-403e-af54-4d4d04d8d033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/span/span</value>
      <webElementGuid>620507e5-8e24-4383-bd31-8bd41224db21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '16 989,-' or . = '16 989,-')]</value>
      <webElementGuid>8dd45146-082e-458e-a8fc-a6668295feea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
