<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanCenaKosiku</name>
   <tag></tag>
   <elementGuidId>0142b858-769d-4a66-9635-8559af516bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f5e20f7d-8380-430b-af71-b2f8da10aa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>7c2173d6-5a54-4da0-b0d2-160c9f255484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16 989 Kč</value>
      <webElementGuid>905850b4-1f52-498d-b3c7-562576ccace3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;price&quot;)</value>
      <webElementGuid>6b752812-60ec-4599-807f-fe167b220e65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='price']</value>
      <webElementGuid>de16b089-a453-40c5-a494-c5d446469082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='basketLink']/span[3]</value>
      <webElementGuid>84db71b9-bebf-4363-806b-fbad40d09161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hledat'])[1]/following::span[3]</value>
      <webElementGuid>68af7b24-fb84-4a6a-a173-4d4a4e52884d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hungary'])[1]/following::span[4]</value>
      <webElementGuid>9d6ed98f-66dd-4099-911c-5d6d0e4b4023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volant Thrustmaster T-GT II'])[2]/preceding::span[2]</value>
      <webElementGuid>adfd66f5-549e-412c-b40b-7e42b76dd0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vše o nákupu'])[1]/preceding::span[5]</value>
      <webElementGuid>82d73db2-190f-4fb5-b113-cd072ccf894e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16 989 Kč']/parent::*</value>
      <webElementGuid>dff0335a-9414-49e7-88e3-35eafc375568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[3]</value>
      <webElementGuid>0b30983e-446c-4744-835d-8e0df71d169d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'price' and (text() = '16 989 Kč' or . = '16 989 Kč')]</value>
      <webElementGuid>2783e88e-2972-4421-aa25-7268f4e7a40c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
